module.exports = {

  env: {
    commonjs: true
  },

  rules: {
    'no-cond-assign': ['error', 'always'],
    'no-console': 'error', //TODO: browser only
    'accessor-pairs': 'warn',
    'block-scoped-var': 'error',
    'complexity': [1, 11],
    'consistent-return': ['error', {treatUndefinedAsUnspecified: true}],
    'default-case': 'error',
    'dot-notation': 'error',
    'eqeqeq': 'error',
    'guard-for-in': 'error',
    'no-alert': 'error',
    'no-caller': 'error',
    'no-div-regex': 'warn',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-floating-decimal': 'error',
    'no-implicit-coercion': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'error',
    'no-iterator': 'error',
    'no-labels': ['error', {allowSwitch: true, allowLoop: true}],
    'no-lone-blocks': 'error',
    'no-loop-func': 'warn',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-new': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'error',
    'no-proto': 'error',
    'no-return-assign': ['error', 'always'],
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unused-expressions': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-void': 'error',
    'no-warning-comments': 'warn',
    'no-with': 'error',
    'radix': 'error',
    'vars-on-top': 'warn',
    'wrap-iife': ['error', 'inside'],
    'yoda': ['error', 'never'],
    'init-declarations': 'warn',
    'no-catch-shadow': 'error',
    'no-label-var': 'error',
    'no-shadow-restricted-names': 'error',
    'no-shadow': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'error',
    'no-use-before-define': 'error',
    'callback-return': ['warn', ['callback', 'cb', 'next', 'done']],
    'global-require': 'error',
    'handle-callback-err': ['error', '^(err|error)$'],
    'no-mixed-requires': 'off',
    'no-new-require': 'error',
    'camelcase': ['error', {'properties': 'always'}],
    'consistent-this': ['error', 'self'],
    'func-style': ['error', 'declaration', {'allowArrowFunctions': true}],
    'no-unneeded-ternary': 'error',
    'no-new-object': 'error',
    'no-nested-ternary': 'error',
    'no-lonely-if': 'error',
    'no-array-constructor': 'error',
    'new-parens': 'error',
    'new-cap': 'error',
    'max-nested-callbacks': ['warn', 4]
  },

  extends: [
    'eslint:recommended'
  ]

};
